# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aac32036e95dc5d5fbf8ead07d0f60045ca8cd6763a4c80a4f890da0fb5c8fec0c88959bc6d75307b22ed39ee4cc94fb448eb1912998f378245e77d06ec77e2d

test:
  secret_key_base: 4e35d4956c37a2b43b299799ebaf2b1d715ed041c60160dba7908f04ba9b237eba5e6a2a7370c360cdb563773a41428cc5b15522b225560f703518939a3503ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
